// This file is generated by sync-versions script

export const BUNITO_VERSION = '^0.0.23';
export const BUN_ENGINE_VERSION = '>=1.3.10';
export const BUN_TYPES_VERSION = '^1.3.0';
export const BIOME_VERSION = '^2.4.16';
export const TYPESCRIPT_VERSION = '^6.0.0';
