import { readdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { styleText } from 'node:util';

export type PackageInfo = {
  name: string;
  version: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  engines?: {
    bun?: string;
  };
};

export type BiomeConfig = {
  $schema: string;
};

const ROOT_PATH = resolve(import.meta.dir, '..');
const WORKSPACE_VERSION_PREFIX = 'workspace:';
const BUNITO_ORG = '@bunito';
const BIOME_CONFIG_FILE = 'biome.base.json';
const VERSIONS_FILE = join('src', 'templates', 'versions.ts');
const PKG_FILE = 'package.json';
const PKG_PATH = join(ROOT_PATH, 'packages');
const PKG_DEPS_KEYS = ['dependencies', 'devDependencies'] as const;

const rootPkgInfo = (await Bun.file(join(ROOT_PATH, PKG_FILE)).json()) as PackageInfo;

const rootVersions = {
  bunito: rootPkgInfo.version,
  bunEngine: rootPkgInfo.engines?.bun ?? 'latest',
  bunTypes: rootPkgInfo.devDependencies?.['@types/bun'] ?? 'latest',
  biome: rootPkgInfo.devDependencies?.['@biomejs/biome'] ?? 'latest',
  typescript: rootPkgInfo.devDependencies?.typescript ?? 'latest',
};

const pkgDepVersion = `${WORKSPACE_VERSION_PREFIX}${rootVersions.bunito}`;

const pkgDirNames = await readdir(PKG_PATH);

for (const pkgName of pkgDirNames) {
  let updated = false;

  const pkgPath = join(PKG_PATH, pkgName);
  const pkgFile = Bun.file(join(pkgPath, PKG_FILE));

  if (!(await pkgFile.exists())) {
    continue;
  }

  const pkgInfo = (await pkgFile.json()) as PackageInfo;

  if (!pkgInfo.name.startsWith(BUNITO_ORG)) {
    continue;
  }

  if (pkgInfo.version !== rootVersions.bunito) {
    pkgInfo.version = rootVersions.bunito;
    updated = true;
  }

  if (pkgInfo?.engines?.bun !== rootVersions.bunEngine) {
    pkgInfo.engines = {
      bun: rootVersions.bunEngine,
    };
    updated = true;
  }

  for (const depsKey of PKG_DEPS_KEYS) {
    const deps = pkgInfo[depsKey];
    if (!deps) {
      continue;
    }

    for (const [name, version] of Object.entries(deps)) {
      if (name.startsWith(BUNITO_ORG) && version !== pkgDepVersion) {
        deps[name] = pkgDepVersion;
        updated = true;
      }
    }
  }

  switch (pkgName) {
    case 'bunito': {
      const biomeConfigFile = Bun.file(join(pkgPath, BIOME_CONFIG_FILE));
      const biomeConfigSchema: BiomeConfig['$schema'] = `https://biomejs.dev/schemas/${rootVersions.biome}/schema.json`;
      const biomeConfig = (await biomeConfigFile.json()) as BiomeConfig;

      if (biomeConfig.$schema !== biomeConfigSchema) {
        biomeConfig.$schema = biomeConfigSchema;

        await biomeConfigFile.write(JSON.stringify(biomeConfig, null, 2));

        updated = true;
      }
      break;
    }

    case 'cli': {
      const versionsFile = Bun.file(join(pkgPath, VERSIONS_FILE));
      const versionsContent = [
        '// This file is generated by sync-versions script',
        '',
        `export const BUNITO_VERSION = '^${rootVersions.bunito}';`,
        `export const BUN_ENGINE_VERSION = '${rootVersions.bunEngine}';`,
        `export const BUN_TYPES_VERSION = '${rootVersions.bunTypes}';`,
        `export const BIOME_VERSION = '^${rootVersions.biome}';`,
        `export const TYPESCRIPT_VERSION = '${rootVersions.typescript}';`,
        '',
      ].join('\n');

      if ((await versionsFile.text()) !== versionsContent) {
        await versionsFile.write(versionsContent);
        updated = true;
      }
      break;
    }
  }

  console.write(`${pkgInfo.name} `);

  if (updated) {
    await pkgFile.write(JSON.stringify(pkgInfo, null, 2));

    console.log(styleText('greenBright', 'UPDATED'));
  } else {
    console.log(styleText('gray', 'SKIPPED'));
  }
}
